// src/mockData.js
export const courses = [
  {
    id: 1,
    title: "React for Beginners",
    description: "Learn React from scratch and build awesome web apps.",
    category: "Web Development",
    level: "Beginner",
    duration: "5h 30m",
    rating: 4.5,
    enrolledCount: 120,
    instructor: "Hema R",
    tags: ["React", "Frontend", "JavaScript"],
    syllabus: ["Introduction to React", "JSX & Components", "State & Props", "Hooks Basics"],
  },
  {
    id: 2,
    title: "Data Science with Python",
    description: "Analyze data and build predictive models using Python.",
    category: "Data Science",
    level: "Intermediate",
    duration: "8h 15m",
    rating: 4.7,
    enrolledCount: 200,
    instructor: "Hariharan",
    tags: ["Python", "Data Analysis", "Machine Learning"],
    syllabus: ["Python Basics", "Pandas & NumPy", "Data Visualization", "Machine Learning Intro"],
  },
  {
    id: 3,
    title: "AI & Machine Learning Fundamentals",
    description: "Dive into AI concepts and ML algorithms with practical examples.",
    category: "AI & Machine Learning",
    level: "Advanced",
    duration: "12h 40m",
    rating: 4.9,
    enrolledCount: 80,
    instructor: "Anusha",
    tags: ["AI", "ML", "Python"],
    syllabus: ["AI Overview", "ML Algorithms", "Deep Learning Basics", "Model Deployment"],
  },
];
